#!/bin/bash


if ! [ -x "$(command -v docker)" ]; then
  echo 1 "docker is not installed see https://docs.docker.com/engine/installation/"
  exit 1
fi

DBOX_VER=$(<../../Version)

usage() {
  echo $#
  echo "Please invoke this script with the IP of the local registry you want pull from."
  echo "Usage: seedFromMirror [registry host name and port]"
  echo "Flags:"
  echo "-h     This help message"
  exit 1
}

if [[ $# < 1 ]] || [[ "$1" == "-h" ]]  # Must have more than 1 args.
then
  usage
fi

seed () {
    docker pull $2
    docker tag $2 $1
}

seed $1/driver-os-monitor tshdataboxsystems2/driver-os-monitor
seed $1/driver-twitter tshdataboxsystems2/driver-twitter
seed $1/driver-sensingkit tshdataboxsystems2/driver-sensingkit
seed $1/app-light-graph tshdataboxsystems2/app-light-graph
seed $1/arbiter:${DBOX_VER} tshdataboxsystems2/arbiter:${DBOX_VER}
seed $1/container-manager:${DBOX_VER} tshdataboxsystems2/container-manager:${DBOX_VER}
seed $1/export-service:${DBOX_VER} tshdataboxsystems2/export-service:${DBOX_VER}
seed $1/app-server tshdataboxsystems2/app-server
seed $1/driver-google-takeout tshdataboxsystems2/driver-google-takeout
seed $1/app-twitter-sentiment tshdataboxsystems2/app-twitter-sentiment
seed $1/base-image-ocaml tshdataboxsystems2/base-image-ocaml
seed $1/driver-phillips-hue tshdataboxsystems2/driver-phillips-hue
seed $1/app-os-monitor tshdataboxsystems2/app-os-monitor
seed $1/driver-tplink-smart-plug tshdataboxsystems2/driver-tplink-smart-plug
seed $1/node:alpine node:alpine

seed $1/databox-redis tlodge/databox-redis
seed $1/databox-sdk tlodge/databox-sdk
seed $1/databox-test-server tlodge/databox-test-server
seed $1/databox-redis tlodge/databox-redis
seed $1/mongo tlodge/mongo